const DATA = {
  "Animales": {
    "Fácil": ["Perro","Gato","León","Tigre","Mono","Pez","Pájaro","Vaca","Cerdo","Caballo","Conejo","Rana","Oso","Pato","Gallina","Ratón","Mariposa","Serpiente","Tortuga","Elefante"],
    "Medio": ["Pingüino","Jirafa","Canguro","Delfín","Cocodrilo","Pulpo","Koala","Gorila","Flamenco","Cebra","Hipopótamo","Camaleón","Murciélago","Pavo real","Erizo","Castor","Panda","Foca","Avestruz","Ardilla"],
    "Difícil": ["Ornitorrinco","Ajolote","Narval","Suricata","Perezoso","Armadillo","Mantis religiosa","Iguana","Medusa","Escorpión","Ciempiés","Mapache","Tejón","Carpincho","Lémur","Antílope","Búfalo","Hiena","Tucán","Salamandra"]
  },
  "Profesiones": {
    "Fácil": ["Doctor","Chef","Policía","Bombero","Profesor","Piloto","Pintor","Cantante","Actor","Dentista","Mecánico","Cartero","Panadero","Granjero","Fotógrafo","Músico","Veterinario","Cajero","Mesero","Carpintero"],
    "Medio": ["Arquitecto","Abogado","Electricista","Plomero","Periodista","Diseñador","Programador","Enfermero","Astronauta","Detective","Jardinero","Peluquero","Fotoperiodista","Geólogo","Biólogo","Ingeniero","Sastre","Barbero","Locutor","Ilustrador"],
    "Difícil": ["Arqueólogo","Meteorólogo","Oceanógrafo","Neurocirujano","Orfebre","Escenógrafo","Criminólogo","Sommelier","Cartógrafo","Restaurador","Entomólogo","Paleontólogo","Coreógrafo","Guionista","Fonoaudiólogo","Topógrafo","Zootecnista","Etnógrafo","Numismático","Herpetólogo"]
  },
  "Comida": {
    "Fácil": ["Pizza","Hamburguesa","Helado","Pastel","Pan","Arroz","Huevo","Sopa","Queso","Manzana","Banano","Taco","Arepa","Pollo","Salchicha","Galleta","Dona","Palomitas","Sandía","Fresa"],
    "Medio": ["Espagueti","Lasaña","Ceviche","Sushi","Ensalada","Hot dog","Nachos","Empanada","Pancakes","Churros","Brownie","Tostada","Croissant","Guacamole","Waffle","Ramen","Paella","Tiramisú","Fondue","Cupcake"],
    "Difícil": ["Ratatouille","Carbonara","Bruschetta","Moussaka","Gnocchi","Crème brûlée","Boeuf bourguignon","Goulash","Tempura","Banh mi","Couscous","Baklava","Tartiflette","Kimchi","Profiteroles","Macaron","Panna cotta","Strudel","Falafel","Gazpacho"]
  },
  "Objetos": {
    "Fácil": ["Mesa","Silla","Cama","Teléfono","Reloj","Llave","Vaso","Cuchara","Lápiz","Libro","Pelota","Paraguas","Zapato","Sombrero","Gafas","Mochila","Cámara","Bicicleta","Cepillo","Espejo"],
    "Medio": ["Aspiradora","Linterna","Tostadora","Maleta","Micrófono","Auriculares","Control remoto","Martillo","Destornillador","Regla","Brújula","Telescopio","Cafetera","Plancha","Calculadora","Patineta","Trípode","Candelabro","Termómetro","Cerradura"],
    "Difícil": ["Proyector","Grúa","Telescopio espacial","Máquina de escribir","Fonógrafo","Máquina de coser","Polaroid","Brújula náutica","Metrónomo","Microscopio","Proyector de cine","Astrolabio","Gramófono","Telégrafo","Barómetro","Estetoscopio","Podómetro","Periscopio","Sismógrafo","Escáner"]
  },
  "Lugares": {
    "Fácil": ["Casa","Escuela","Parque","Playa","Iglesia","Hospital","Cine","Restaurante","Piscina","Granja","Zoológico","Tienda","Aeropuerto","Estadio","Hotel","Biblioteca","Museo","Circo","Montaña","Bosque"],
    "Medio": ["Castillo","Volcán","Desierto","Isla","Faro","Estación de tren","Supermercado","Universidad","Estación espacial","Acuario","Catarata","Puente","Puerto","Camping","Parque de diversiones","Cafetería","Teatro","Oficina","Gimnasio","Cueva"],
    "Difícil": ["Pirámides de Egipto","Torre Eiffel","Machu Picchu","Gran Cañón","Antártida","Selva amazónica","Coliseo romano","Taj Mahal","Stonehenge","Estación polar","Observatorio","Catacumbas","Muralla China","Arrecife de coral","Templo maya","Fiordo","Glaciar","Volcán submarino","Palacio real","Ruinas antiguas"]
  },
  "Acciones": {
    "Fácil": ["Correr","Saltar","Dormir","Comer","Beber","Nadar","Bailar","Llorar","Reír","Cantar","Caminar","Leer","Escribir","Cocinar","Limpiar","Barrer","Saltar la cuerda","Aplaudir","Silbar","Trepar"],
    "Medio": ["Pescar","Patinar","Esquiar","Bucear","Trotar","Pintar","Besar","Abrazar","Estornudar","Toser","Peinarse","Cepillarse","Planchar","Bostezar","Regar plantas","Lavar platos","Hacer ejercicio","Tomar una foto","Abrir un regalo","Inflar un globo"],
    "Difícil": ["Hacer malabares","Montar en monociclo","Armar un rompecabezas","Tocar batería","Hacer yoga","Pescar un pez","Perder el equilibrio","Escalar una pared","Hacer magia","Manejar una excavadora","Hacer una reverencia","Tocar el violín","Hacer snowboard","Montar a caballo","Lanzar un boomerang","Hacer una pirueta","Atrapar una mariposa","Hacer una cometa","Plantar un árbol","Construir un muñeco de nieve"]
  },
  "Películas y personajes": {
    "Fácil": ["Superman","Batman","Spider-Man","Hulk","Shrek","Barbie","Tarzán","Cenicienta","Pinocho","Aladdín","Elsa","Nemo","Simba","Woody","Buzz Lightyear","Minion","Mickey Mouse","Pikachu","Harry Potter","Kung Fu Panda"],
    "Medio": ["Jack Sparrow","Indiana Jones","Sherlock Holmes","Mulan","Rapunzel","Hércules","Ariel","Willy Wonka","Rocky","Terminator","Godzilla","King Kong","Darth Vader","Yoda","Gandalf","Frodo","Joker","Deadpool","Iron Man","Capitán América"],
    "Difícil": ["El Sombrerero Loco","Mary Poppins","Beetlejuice","Forrest Gump","Neo","John Wick","Gollum","Drácula","Frankenstein","El Principito","Cruella","Maléfica","Hannibal Lecter","Amélie","Tony Stark","Wednesday Addams","Jack Skellington","Buzz Aldrin","Don Vito Corleone","Rocky Balboa"]
  },
  "Naturaleza": {
    "Fácil": ["Sol","Luna","Nube","Lluvia","Árbol","Flor","Río","Lago","Mar","Nieve","Volcán","Montaña","Piedra","Arena","Hoja","Tronco","Cueva","Isla","Arcoíris","Estrella"],
    "Medio": ["Tormenta","Huracán","Tornado","Cascada","Glaciar","Arrecife","Bosque","Selva","Desierto","Eclipse","Aurora boreal","Marea","Trueno","Relámpago","Avalancha","Terremoto","Géiser","Acantilado","Pantano","Pradera"],
    "Difícil": ["Erosión","Erupción volcánica","Placa tectónica","Ciclo del agua","Corriente marina","Arco volcánico","Falla geológica","Bosque de manglar","Cañón submarino","Bioluminiscencia","Deslizamiento de tierra","Formación de nubes","Ojo del huracán","Aurora polar","Corriente de lava","Duna de arena","Glaciar derritiéndose","Mar de nubes","Anillo de fuego","Maremoto"]
  },
  "Deportes": {
    "Fácil": ["Fútbol","Tenis","Golf","Béisbol","Baloncesto","Voleibol","Natación","Boxeo","Ciclismo","Atletismo","Bolos","Surf","Esquí","Patinaje","Gimnasia","Hockey","Rugby","Bádminton","Karate","Pesca"],
    "Medio": ["Escalada","Esgrima","Halterofilia","Triatlón","Maratón","Waterpolo","Buceo","Polo","Remo","Canotaje","Judo","Taekwondo","Skateboarding","Snowboard","Tiro con arco","Lucha","BMX","Parapente","Motocross","Equitación"],
    "Difícil": ["Pentatlón moderno","Decatlón","Curling","Skeleton","Biatlón","Lacrosse","Críquet","Kitesurf","Windsurf","Ciclismo de pista","Gimnasia rítmica","Salto ecuestre","Esquí acrobático","Kayak de aguas bravas","Marcha atlética","Surf de remo","Tiro deportivo","Bobsleigh","Sambo","Ultimate frisbee"]
  }
};

// Banco ampliado: se mezcla con las palabras base para aumentar muchísimo la variedad.
const EXTRA_BANKS = {
  "Animales": {
    "Fácil": "Cabra Oveja Burro Zorro Lobo Ciervo Ardilla Hámster Panda Koala Gorila Cangrejo Tiburón Ballena Orca Morsa Foca Loro Canario Tucán Búho Águila Cuervo Pavo real Flamenco Jirafa Cebra Rinoceronte Camello Canguro Cabra montés Oso polar Oso panda Suricata Nutria Castor Mapache Jabalí Reno Alce Búfalo Alpaca Llama Ñu Iguana Lagarto Gecko Rana Sapo Salamandra Tortuga marina Pez payaso Pez globo Caballito de mar Estrella de mar Abeja Hormiga Avispa Mosca Mosquito Araña Caracol Oruga Escarabajo Libélula Grillo Saltamontes Polilla Gusano Mariposa Mantis".split(' '),
    "Medio": "Orca Narval Beluga Manatí Dugongo Albatros Cóndor Halcón Buitre Garza Cisne Carpintero Colibrí Tucán Iguana marina Dragón de Komodo Gecko Boa Pitón Anaconda Cobra Cascabel Tortuga gigante Axolote Salamandra Mantis Escarabajo rinoceronte Escorpión Tarántula Cigarra Avispa Polilla Gusano de seda Cangrejo ermitaño Calamar Sepia Nautilo Ostra Mejillón Almeja Pez espada Pez martillo Pez león Barracuda Piraña Anguila eléctrica Carpincho Lémur Mandril Orangután Babuino Tapir Okapi Impala Mangosta Chacal Coyote Puma Jaguar Leopardo Antílope Bisonte Tejón Comadreja Pangolín Wombat Quokka Aye-aye Mono narigudo Camello bactriano Yak".split(' '),
    "Difícil": "Ornitorrinco Quokka Wombat Equidna Pangolín Saiga Bongo Kudu Orix Okapi Aye-aye Tarsero Manul Caracal Serval Binturong Civeta Geneta Kinkajú Tamandúa Oso hormiguero Lobo de crin Zorro fénec Zorro ártico Lince Muntíaco Diablo de Tasmania Dugongo Narval Calamar vampiro Calamar gigante Pulpo dumbo Camarón mantis Cangrejo herradura Pez remo Pez piedra Pez luna Pez arquero Mola mola Pez abisal Anguila jardinera Tiburón duende Tiburón peregrino Pez dragón Pez hacha Nautilo Escorpión látigo Tardígrado Planaria Insecto palo Insecto hoja Escarabajo joya Escarabajo pelotero Polilla atlas Mariposa atlas Chinche palo Mosca de la fruta Avispa parasitoide Hormiga cortadora de hojas Salamandra gigante Rana dardo venenosa Tuátara Gavial Caimán negro Serpiente taipán Mamba negra Cobra real Serpiente coral".split(' ')
  },
  "Profesiones": {
    "Fácil": "Profesor Enfermero Cocinero Panadero Repartidor Conductor Taxista Cartero Jardinero Mecánico Electricista Plomero Albañil Pintor Fotógrafo Camarógrafo Cantante Actor Bailarín Músico DJ Locutor Vendedor Cajero Mesero Barista Peluquero Barbero Costurero Sastre Florista Carnicero Granjero Pescador Apicultor Entrenador Árbitro Socorrista Salvavidas Guía turístico Recepcionista Secretario Contador Diseñador Programador Técnico Guardia Portero Conserje Bibliotecario Bibliotecaria Entrenador personal Masajista Voluntario Bombero Policía Soldado Marinero Piloto Azafata Chef Veterinario Dentista Abogado Arquitecto Ingeniero Periodista Escritor Escultor Mago Payaso Modelo".split(' '),
    "Medio": "Químico Físico Matemático Economista Historiador Antropólogo Biólogo Geólogo Botánico Zoólogo Meteorólogo Oceanógrafo Veterinario Odontólogo Cirujano Paramédico Controlador aéreo Capitán de barco Maquinista Chef pastelero Sommelier Barista Mixólogo Ceramista Joyero Orfebre Grabador Tatuador Estilista Maquillador Coreógrafo Guionista Editor Productor Director Camarógrafo Sonidista Animador Diseñador industrial Desarrollador web Analista Administrador Gerente Consultor Traductor Intérprete Archivista Curador Entrenador deportivo Preparador físico Nutricionista Terapeuta Optometrista Podólogo Radiólogo Anestesiólogo Pediatra Cardiólogo Dermatólogo Farmacéutico Técnico de laboratorio Técnico de redes Tasador Agente inmobiliario Aduanero Notario Fiscal Diplomático Piloto de carreras Mecánico de competición Adiestrador de perros Fotoperiodista".split(' '),
    "Difícil": "Arqueólogo Meteorólogo Oceanógrafo Neurocirujano Criminólogo Cartógrafo Restaurador Entomólogo Paleontólogo Fonoaudiólogo Topógrafo Zootecnista Etnógrafo Numismático Herpetólogo Astrofísico Sismólogo Vulcanólogo Glaciólogo Hidrólogo Limnólogo Micólogo Genetista Microbiólogo Neurocientífico Bioquímico Toxicólogo Patólogo Endocrinólogo Neonatólogo Neuropsicólogo Epidemiólogo Inmunólogo Radioterapeuta Traumatólogo Otorrinolaringólogo Oftalmólogo Protesista Audiológo Astrónomo Cosmólogo Astrobiólogo Ingeniero aeroespacial Ingeniero nuclear Ingeniero biomédico Ingeniero naval Ingeniero ambiental Urbanista Paisajista Tipógrafo Calígrafo Restaurador de arte Paleógrafo Epigrafista Criptógrafo Forense Criminalista Grafólogo Detective privado Mediador Actuario Auditor Analista financiero Científico de datos Arquitecto de software Ingeniero DevOps Especialista en ciberseguridad Administrador de bases de datos Ingeniero agrónomo Ingeniero geotécnico Ingeniero mecatrónico".split(' ')
  },
  "Comida": {
    "Fácil": "Arroz Pasta Sopa Pizza Hamburguesa Perro caliente Tacos Arepa Empanada Pollo Carne Pescado Huevo Queso Pan Galleta Torta Pastel Helado Chocolate Caramelo Dona Churro Brownie Cupcake Waffle Pancake Cereal Yogur Leche Jugo Limonada Café Té Manzana Banano Pera Mango Piña Papaya Fresa Uva Naranja Sandía Coco Aguacate Tomate Papa Zanahoria Maíz Frijoles Lentejas Arvejas Brócoli Lechuga Pepino Cebolla Ajo Champiñón Pizza Sushi Nachos Popcorn Palomitas Tamal Buñuelo Pandebono Salchipapa".split(' '),
    "Medio": "Espagueti Lasaña Ravioli Canelones Carbonara Risotto Paella Ceviche Sushi Sashimi Ramen Pho Pad thai Curry Naan Tikka masala Bibimbap Kimchi Tempura Teriyaki Maki Nigiri Onigiri Dim sum Gyoza Shawarma Kebab Falafel Hummus Tabulé Guacamole Quesadilla Burrito Enchilada Fajitas Mole Pozole Pupusas Feijoada Churrasco Milanesa Goulash Ratatouille Bruschetta Caprese Focaccia Gelato Cannoli Tiramisú Panna cotta Cheesecake Red velvet Tres leches Macaron Éclair Profiteroles Baklava Strudel Mousse Parfait Crepa Soufflé Fondue Raclette Ajiaco Sancocho Bandeja paisa Lechona Arroz con pollo Mote de queso".split(' '),
    "Difícil": "Moussaka Gnocchi Crème brûlée Boeuf bourguignon Tartiflette Profiteroles Panna cotta Strudel Gazpacho Bouillabaisse Coq au vin Cassoulet Confit de pato Croque monsieur Quiche Lorraine Raclette Escargots Soufflé Beef Wellington Osso buco Polenta Arancini Burrata Carpaccio Vitello tonnato Caponata Panzanella Ramen tonkotsu Okonomiyaki Takoyaki Sukiyaki Shabu-shabu Yakitori Unagi Chawanmushi Mapo tofu Dan dan noodles Xiaolongbao Pato pekinés Char siu Japchae Bulgogi Tteokbokki Tom yum Tom kha Massaman curry Pad see ew Som tam Laksa Satay Nasi goreng Manti Shakshuka Baba ganoush Dolma Spanakopita Kibbeh Ceviche nikkei Tiradito Anticucho Lomo saltado Causa limeña Sachertorte Linzer torte Kouign-amann Clafoutis Madeleine Financier Opera cake Mille-feuille Saint-honoré Paris-brest Crêpe Suzette Pavlova Banoffee Mochi Dorayaki Taiyaki Dango".split(' ')
  },
  "Objetos": {
    "Fácil": "Mesa Silla Cama Sofá Almohada Cobija Toalla Lámpara Reloj Teléfono Computador Teclado Ratón Televisor Control remoto Cámara Libro Cuaderno Lápiz Bolígrafo Borrador Regla Tijeras Pegante Mochila Bolso Cartera Billetera Llave Candado Vaso Taza Plato Cuchara Tenedor Cuchillo Olla Sartén Escoba Trapeador Aspiradora Plancha Peine Cepillo Espejo Paraguas Sombrero Zapato Botella Termo Vela Globo Pelota Juguete Muñeca Carrito Bicicleta Patineta Cometa Dados Cartas Dominó Ajedrez Guitarra Piano Tambor Micrófono Audífonos Radio Parlante Linterna Martillo Destornillador Taladro Cinta métrica Caja Florero Maceta Planta Cuadro Cortina Alfombra Ventana Puerta Ventilador Refrigerador Microondas Licuadora Tostadora".split(' '),
    "Medio": "Aspiradora Tostadora Maleta Micrófono Auriculares Control remoto Martillo Destornillador Brújula Telescopio Cafetera Plancha Calculadora Patineta Trípode Candelabro Termómetro Cerradura Taladro Sierra Nivel Alicates Llave inglesa Engrapadora Perforadora Archivador Carpeta Proyector Impresora Escáner Router Disco duro Memoria USB Tableta Consola Joystick Cargador Batería Power bank Cámara web Dron GPS Binoculares Megáfono Walkie-talkie Extintor Botiquín Muletas Silla de ruedas Balanza Báscula Termo Sacacorchos Abrelatas Colador Rallador Batidor Rodillo Molinillo Mortero Cucharón Espátula Pinzas Wok Vaporera Tabla de cortar Perchero Tendedero Humidificador Deshumidificador Purificador Calentador Radiador Plancha de cabello Rizador Máquina de afeitar Máquina de coser Caja fuerte Cámara de seguridad Detector de humo Timbre Intercomunicador Portarretratos Atril Pizarra".split(' '),
    "Difícil": "Proyector Grúa Telescopio espacial Máquina de escribir Fonógrafo Máquina de coser Polaroid Brújula náutica Metrónomo Microscopio Proyector de cine Astrolabio Gramófono Telégrafo Barómetro Estetoscopio Podómetro Periscopio Sismógrafo Teodolito Sextante Cronógrafo Espectrómetro Osciloscopio Multímetro Calibrador Micrómetro Torquímetro Manómetro Anemómetro Higrómetro Pluviómetro Altímetro Telémetro Visor nocturno Cámara térmica Sonar Radar Electrocardiógrafo Desfibrilador Centrífuga Incubadora Autoclave Micrótomo Endoscopio Ecógrafo Resonancia magnética Tomógrafo Bomba de infusión Prótesis Exoesqueleto Robot industrial Brazo robótico Impresora 3D Cortadora láser Plotter Router industrial Servidor NAS Switch Firewall Satélite Rover Módulo lunar Sonda espacial Telescopio reflector Planetario Máquina arcade Pinball Caja registradora Terminal POS Máquina expendedora Contenedor marítimo Montacargas Excavadora Retroexcavadora Bulldozer Mezcladora de cemento Compresor Generador eléctrico Panel solar Turbina eólica Transformador Subestación Pararrayos Semáforo Parquímetro Cabina telefónica Buzón Máquina de fax Proyector holográfico".split(' ')
  },
  "Lugares": {
    "Fácil": "Casa Escuela Colegio Parque Playa Iglesia Hospital Cine Restaurante Piscina Granja Zoológico Tienda Aeropuerto Estadio Hotel Biblioteca Museo Circo Montaña Bosque Supermercado Farmacia Panadería Cafetería Banco Oficina Gimnasio Universidad Estación de bus Estación de tren Parque infantil Cancha Teatro Plaza Mercado Feria Camping Río Lago Isla Desierto Jardín Huerta Garaje Cocina Baño Habitación Sala Balcón Terraza Patio Ascensor Escaleras Pasillo Cementerio Puerto Faro Puente Cueva Cascada Volcán Valle Colina Selva Pradera Estación de policía Estación de bomberos Juzgado Cárcel Embajada Consulado Terminal Parqueadero Galería Discoteca Bar Spa Salón de belleza Consultorio Clínica Laboratorio Acuario Bolera Estación de gasolina Taller Lavadero de carros Tienda de juguetes Librería Heladería Peluquería".split(' '),
    "Medio": "Castillo Volcán Desierto Isla Faro Estación de tren Supermercado Universidad Estación espacial Acuario Catarata Puente Puerto Camping Parque de diversiones Cafetería Teatro Oficina Gimnasio Cueva Palacio Templo Monasterio Catedral Mezquita Sinagoga Pirámide Ruinas Fortaleza Muralla Ciudad antigua Pueblo fantasma Aldea Rascacielos Metro Estación de metro Hospital infantil Clínica veterinaria Laboratorio Observatorio Planetario Campus Biblioteca antigua Estudio de cine Set de televisión Estudio de grabación Sala de conciertos Ópera Anfiteatro Coliseo Estadio olímpico Circuito de carreras Campo de golf Pista de esquí Puerto deportivo Marina Astillero Terminal de cruceros Fábrica Almacén Planta eléctrica Mina Cantera Granja de animales Viñedo Plantación Reserva natural Parque nacional Safari Selva tropical Manglar Pantano Glaciar Cañón Acantilado Fiordo Desfiladero Oasis Duna Playa tropical Isla volcánica Arrecife Cueva de hielo Cascada gigante Presa Represa Embalse Central hidroeléctrica Molino Faro costero Torre de control Búnker".split(' '),
    "Difícil": "Pirámides de Egipto Torre Eiffel Machu Picchu Gran Cañón Antártida Selva amazónica Coliseo romano Taj Mahal Stonehenge Estación polar Observatorio Catacumbas Muralla China Arrecife de coral Templo maya Fiordo Glaciar Volcán submarino Palacio real Petra Angkor Wat Chichén Itzá Teotihuacán Acrópolis de Atenas Monte Fuji Salar de Uyuni Islas Galápagos Cataratas del Niágara Cataratas Victoria Serengeti Sahara Atacama Patagonia Groenlandia Islandia Madagascar Borneo Nueva Zelanda Gran Barrera de Coral Mar Muerto Everest Kilimanjaro Aconcagua Alpes Himalaya Amazonas Nilo Río Yangtsé Delta del Mekong Canal de Panamá Canal de Suez Estrecho de Gibraltar Ciudad Prohibida Palacio de Versalles Buckingham Palace Ópera de Sídney Burj Khalifa Empire State Building Times Square Las Vegas Strip Hollywood Silicon Valley Wall Street Pentágono Casa Blanca Capitolio Vaticano Notre Dame Sagrada Familia Puente Golden Gate Puente de Brooklyn Torre de Pisa Big Ben Alhambra Monte Saint-Michel Canal de Venecia Isla de Pascua Líneas de Nazca Valle de los Reyes Base lunar Estación espacial internacional Centro de control espacial Laboratorio submarino Ciudad submarina Búnker nuclear Plataforma petrolera Parque jurásico Castillo medieval Aldea vikinga Templo budista Monasterio tibetano Ciudad perdida".split(' ')
  },
  "Acciones": {
    "Fácil": "Correr Saltar Dormir Comer Beber Nadar Bailar Llorar Reír Cantar Caminar Leer Escribir Cocinar Limpiar Barrer Aplaudir Silbar Trepar Abrir Cerrar Sentarse Levantarse Caerse Empujar Jalar Lanzar Atrapar Patear Golpear Abrazar Besar Saludar Despedirse Llamar Hablar Escuchar Mirar Señalar Gatear Rodar Girar Agacharse Estirarse Respirar Toser Estornudar Bostezar Despertarse Vestirse Desvestirse Lavarse Cepillarse Peinarse Afeitarse Maquillarse Masticar Cortar Pelar Revolver Servir Brindar Cargar Descargar Subir Bajar Entrar Salir Cruzar Esperar Buscar Encontrar Perder Ganar Jugar Dibujar Pintar Fotografiar Grabar Barrer Trapear Lavar Secar Planchar Doblar Regar Sembrar Cavar Pescar Remar Pedalear".split(' '),
    "Medio": "Pescar Patinar Esquiar Bucear Trotar Pintar Besar Abrazar Estornudar Toser Peinarse Cepillarse Planchar Bostezar Regar plantas Lavar platos Hacer ejercicio Tomar una foto Abrir un regalo Inflar un globo Montar bicicleta Montar patineta Montar a caballo Conducir Estacionar Cruzar la calle Esperar el bus Tomar el metro Comprar comida Pagar una cuenta Contar dinero Firmar un documento Escribir una carta Enviar un mensaje Hacer una llamada Tomar una selfie Grabar un video Escuchar música Tocar guitarra Tocar piano Tocar batería Cantar en público Bailar salsa Bailar tango Hacer yoga Meditar Levantar pesas Saltar obstáculos Escalar Hacer surf Jugar fútbol Jugar tenis Lanzar una bola Batear Encestar Nadar de espaldas Hacer clavados Cocinar una receta Hacer una torta Preparar café Servir una mesa Lavar un carro Cambiar una llanta Arreglar una bicicleta Clavar un clavo Pintar una pared Armar un mueble Regar el jardín Podar un árbol Cortar el césped Pasear al perro Bañar al perro Alimentar una mascota Dar un regalo Recibir un regalo Romper una piñata Soplar velas Hacer una reverencia Chocar los cinco Dar un abrazo Lanzar un beso Guiñar un ojo Hacer silencio Pedir ayuda Levantar la mano Tomar apuntes Estudiar Hacer una presentación Borrar una pizarra Ordenar una habitación Hacer la cama Tender ropa".split(' '),
    "Difícil": "Hacer malabares Montar en monociclo Armar un rompecabezas Tocar batería Hacer yoga Pescar un pez Perder el equilibrio Escalar una pared Hacer magia Manejar una excavadora Hacer una reverencia Tocar el violín Hacer snowboard Montar a caballo Lanzar un boomerang Hacer una pirueta Atrapar una mariposa Hacer una cometa Plantar un árbol Construir un muñeco de nieve Hacer desaparecer una moneda Caminar sobre una cuerda Escapar de un laberinto Buscar un tesoro Descifrar un mapa Leer una brújula Montar una carpa Encender una fogata Apagar una fogata Remar contra corriente Navegar en velero Hacer windsurf Practicar esgrima Luchar en judo Romper una tabla Hacer una voltereta Hacer una parada de manos Caminar en puntillas Imitar un robot Imitar un zombi Imitar un mono Imitar un dinosaurio Hacer una estatua Posar para una foto Dirigir una orquesta Actuar en una obra Presentar un programa Hacer una entrevista Investigar una pista Interrogar a un sospechoso Resolver un misterio Buscar huellas Tomar una muestra Usar un microscopio Observar las estrellas Mirar por un telescopio Despegar en un cohete Caminar en la Luna Pilotar un avión Aterrizar un avión Controlar el tráfico aéreo Manejar una grúa Construir una casa Derribar una pared Soldar una pieza Reparar un motor Cambiar una batería Programar un robot Imprimir en 3D Hacer una escultura Restaurar una pintura Revelar una fotografía Hacer una animación Editar una película Grabar una película Dirigir una película Escribir un guion Hacer doblaje Traducir un texto Interpretar un idioma Dar un discurso Debatir Negociar Firmar un contrato Subastar un objeto Hacer una auditoría Analizar una muestra Operar a un paciente Hacer una radiografía Realizar una ecografía Rescatar a alguien Apagar un incendio".split(' ')
  },
  "Ropa y accesorios": {
    "Fácil":"Camisa Pantalón Vestido Falda Zapato Tenis Botas Sandalias Sombrero Gorra Bufanda Guantes Chaqueta Abrigo Medias Cinturón Corbata Pijama Traje de baño Bata Delantal Mochila Bolso Cartera Billetera Gafas Reloj Anillo Collar Pulsera Aretes Diadema Corona Paraguas Impermeable Disfraz Uniforme Corbatín Pañuelo Chaleco Suéter Sudadera Short Bermuda Jeans Leggings Blusa Top Pantufla Chancla Tacón Correa Gorro Visera Broche Lazo Babero Bikini Gafas de sol Casco Rodilleras Coderas Chaleco salvavidas Capa Máscara".split(' '),
    "Medio":"Gabardina Impermeable Poncho Kimono Sari Kilt Toga Esmoquin Vestido de gala Traje de buzo Traje de neopreno Chaleco salvavidas Casco de bicicleta Casco de motocicleta Casco de astronauta Máscara de esquí Gafas de natación Gafas de buceo Aletas Botas de esquí Patines Guantes de portero Guantes de boxeo Protector bucal Rodilleras Coderas Tobilleras Muñequeras Cinturón de karate Tirantes Gemelos Broche Prendedor Boina Sombrero de copa Sombrero vaquero Sombrero mexicano Turbante Velo Diadema Horquilla Pasador Estola Capa Manto Sarong Llavero Riñonera Bandolera Maletín Portafolios Mochila de viaje Clutch Neceser Estuche de gafas Paraguas plegable Bastón Monóculo Reloj de bolsillo Medalla Insignia Pin Pulsera inteligente Collar Anillo de compromiso Alianza Pendientes Tobillera Máscara de carnaval Antifaz Disfraz de superhéroe Disfraz de pirata Disfraz de payaso Disfraz de vampiro Uniforme de policía Uniforme de bombero Uniforme de chef Uniforme militar Uniforme deportivo Poncho andino Sombrero de paja Botas de vaquero Capa de lluvia".split(' '),
    "Difícil":"Armilla Cofia Pechera Jabot Frac Levita Chaleco de pescador Parka Anorak Pantalón cargo Pantalón bombacho Sarouel Hanbok Dirndl Cheongsam Ao dai Abaya Burka Keffiyeh Fez Sombrero cordobés Sombrero panamá Bombín Fedora Canotier Fascinador Tocado Pamela Montera Turbante sij Kippah Borsalino Monóculo Lorgnette Gemelos de camisa Alfiler de corbata Pasador de corbata Faja Sash Polaina Espinillera Canillera Faja deportiva Corsé Crinolina Miriñaque Enagua Bata de laboratorio Escafandra Traje de astronauta Traje de apicultor Traje ignífugo Traje de esgrima Traje de sumo Armadura Cota de malla Yelmo Penacho Máscara de gas Máscara de soldador Respirador Arnés de escalada Paracaídas Chaleco táctico Cinturón de herramientas Funda de guitarra Bandolera militar Mochila de hidratación Riñonera de corredor Porta credencial Tarjetero Estuche de maquillaje Neceser de viaje Sombrerera Joyero Alhajero Brazalete Gargantilla Broche victoriano Camafeo Tiara Diadema medieval Velo de novia Guantes largos Guantes sin dedos Mitones Botines Mocasines Oxford Loafers Zuecos Alpargatas Espadrilles Tacones de aguja Plataformas Polainas de nieve Aletas de buceo".split(' ')
  },
  "Transporte": {
    "Fácil":"Carro Bus Taxi Moto Bicicleta Avión Barco Tren Metro Camión Ambulancia Camioneta Tractor Helicóptero Submarino Patineta Patines Scooter Lancha Velero Canoa Kayak Ferry Crucero Yate Teleférico Tranvía Mototaxi Triciclo Carreta Caballo Camello Globo aerostático Bus escolar Bus turístico Bus articulado Camión de basura Camión de bomberos Grúa Excavadora Montacargas Tren de carga Tren bala Avioneta Jet Cohete Dron Segway Monociclo Cuatrimoto Buggy Go-kart Limusina Convertible Furgoneta Minibús Autocar Trolebús Funicular Tren de vapor Locomotora Vagón Motocicleta Ciclomotor Scooter eléctrico Bicicleta de montaña Bicicleta de carrera Carro de golf Trineo Trineo de perros Motonieve Tabla de surf".split(' '),
    "Medio":"Motocicleta Tren bala Avión de carga Hidroavión Helicóptero Submarino Yate Catamarán Velero Ferry Crucero Lancha rápida Moto acuática Kayak Canoa Rafting Teleférico Funicular Monorraíl Tranvía Trolebús Tren de vapor Locomotora Vagón restaurante Metro automático Bus articulado Camión cisterna Camión grúa Camión de bomberos Camión de basura Camión minero Excavadora Bulldozer Retroexcavadora Montacargas Tractor Cosechadora Segadora Ambulancia aérea Patrulla policial Carro de carreras Fórmula 1 Kart Buggy ATV Cuatrimoto Moto de nieve Trineo de perros Teleférico de montaña Telesilla Funicular de montaña Globo aerostático Dirigible Zeppelin Avioneta Planeador Parapente Paramotor Ultraligero Dron Rover Nave espacial Cohete Cápsula espacial Transbordador espacial Hovercraft Aerodeslizador Bote salvavidas Balsa Catamarán Trimarán Barco pesquero Barco de carga Portacontenedores Petrolero Remolcador Ferry de autos Barco de vapor Góndola Bicicleta tándem Bicicleta BMX Bicicleta de montaña Patinete eléctrico Segway Rickshaw Tuk-tuk Carro de caballos Diligencia".split(' '),
    "Difícil":"Hovercraft Aerodeslizador Hidroavión Avión anfibio Planeador Ultraligero Autogiro Dirigible Zeppelin Paramotor Paracaídas de emergencia Transbordador espacial Cápsula espacial Rover marciano Vehículo lunar Cohete reutilizable Lanzadera orbital Satélite Sonda espacial Dron submarino ROV submarino AUV Submarino nuclear Submarino de investigación Batiscafo Sumergible Catamarán de vela Trimarán Hidroala Lancha hidroplano Barco rompehielos Portaaviones Destructor Fragata Corbeta Patrullera Buque hospital Barco cablero Draga Remolcador de puerto Barcaza Portacontenedores Granelero Petrolero Gasero Ro-Ro Ferry de alta velocidad Tren maglev Tren bala Monorraíl suspendido Funicular Telesilla Teleférico urbano Tranvía histórico Trolebús Metro sin conductor Tren de levitación magnética Locomotora diésel Locomotora eléctrica Locomotora de vapor Tren de cremallera Tren minero Vehículo de orugas Tanque Vehículo anfibio Blindado Camión minero Perforadora móvil Grúa torre móvil Grúa telescópica Cosechadora combinada Tractor oruga Segadora autopropulsada Vehículo de rescate Ambulancia todoterreno Camión portacoches Camión hormigonera Camión plataforma Camión volquete Camión forestal Auto de rally Dragster Kart de competición Moto de trial Moto de enduro Moto de speedway Bicicleta de pista Bicicleta de contrarreloj Bicicleta de descenso Bicicleta de ciclocross Triciclo de carga Rickshaw japonés Tuk-tuk eléctrico Diligencia antigua Carruaje real Góndola veneciana Balsa de rafting".split(' ')
  },
  "Casa y hogar": {
    "Fácil":"Cocina Baño Sala Habitación Jardín Patio Garaje Balcón Terraza Sofá Cama Mesa Silla Televisor Nevera Horno Lavadora Ducha Bañera Lavamanos Inodoro Espejo Armario Cajón Estante Almohada Cobija Cortina Alfombra Lámpara Ventana Puerta Escaleras Ascensor Planta Florero Cuadro Reloj Cojín Toalla Jabón Cepillo Escoba Trapeador Aspiradora Plancha Cafetera Tostadora Licuadora Microondas Plato Vaso Taza Cuchara Tenedor Cuchillo Olla Sartén Colador Tabla de cortar Basurero Caja Cesta Perchero Zapatero Escritorio Computador Herramientas Martillo Destornillador Taladro Maceta Manguera Regadera Parrilla Hamaca Piscina Columpio Tobogán Acuario Ventilador Aire acondicionado Radio Parlante Libro Juguete Bicicleta".split(' '),
    "Medio":"Aspiradora robot Lavavajillas Secadora Horno eléctrico Horno de gas Freidora de aire Olla a presión Arrocera Cafetera espresso Batidora Procesador de alimentos Extractor Calentador de agua Termotanque Purificador de aire Humidificador Deshumidificador Aire acondicionado portátil Ventilador de techo Robot de cocina Máquina de coser Caja fuerte Cámara de seguridad Detector de humo Detector de monóxido Timbre inteligente Cerradura electrónica Intercomunicador Router Servidor doméstico Impresora Escáner Proyector Consola de videojuegos Barra de sonido Estantería Biblioteca Vitrina Cómoda Buró Cabecero Cuna Mecedora Sillón reclinable Mesa de centro Mesa auxiliar Escritorio Archivador Pizarra Perchero Zapatero Organizador Caja de herramientas Escalera Banco de trabajo Taladro Sierra eléctrica Lijadora Compresor Hidrolavadora Manguera enrollable Aspersor Cortacésped Podadora Barbacoa Horno de pizza Fogón Parrilla Jacuzzi Sauna Invernadero Pérgola Fuente Estanque Huerto Compostera Colmena Gallinero Caseta Buzón Portón eléctrico Garaje automático Persiana Mosquitero Cortina enrollable Domótica Panel solar Batería doméstica Generador Chimenea Estufa de leña Calefacción central Radiador Termostato Ventana panorámica".split(' '),
    "Difícil":"Domótica Casa inteligente Sistema de automatización Calefacción geotérmica Paneles solares Batería doméstica Sistema fotovoltaico Colector solar Bomba de calor Caldera Termotanque solar Descalcificador Purificador de agua Sistema de ósmosis Tanque de agua Cisterna Bomba de agua Sistema de riego automático Aspersor programable Invernadero automatizado Compostera Biodigestor Techo verde Jardín vertical Muro vegetal Pérgola bioclimática Persiana motorizada Cortina automatizada Puerta corrediza automática Portón eléctrico Cerradura biométrica Videoportero Sistema de alarma Sensor de movimiento Sensor de apertura Detector de fugas Detector de humo Detector de gas Cámara PTZ Cámara con visión nocturna Servidor NAS Red mesh Punto de acceso Router Wi-Fi Switch PoE Rack de comunicaciones Home theater Proyector 4K Pantalla retráctil Barra de sonido Sistema multiroom Tocadiscos Amplificador Subwoofer Piano digital Aspiradora central Robot cortacésped Robot limpia piscinas Lavavajillas inteligente Horno de vapor Horno combinado Sous-vide Deshidratador Fermentador Máquina de helado Máquina de pan Molino de café Cafetera de sifón Espumador de leche Encimera de inducción Campana extractora Triturador de alimentos Compactador de basura Lavadora inteligente Secadora con bomba de calor Planchado vertical Máquina de vapor Armario climatizado Bodega de vinos Sauna infrarroja Baño turco Jacuzzi exterior Piscina infinita Piscina climatizada Fuente ornamental Estanque koi Riego por goteo Huerto hidropónico Casa del árbol Taller doméstico".split(' ')
  },
  "Escuela y oficina": {
    "Fácil":"Lápiz Borrador Cuaderno Libro Regla Tijeras Pegante Marcador Pizarra Mochila Escritorio Silla Computador Teclado Ratón Impresora Calculadora Mapa Globo terráqueo Profesor Estudiante Clase Examen Tarea Recreo Biblioteca Salón Patio Campana Uniforme Lonchera Cartuchera Carpeta Hoja Papel Crayón Pincel Pintura Compás Transportador Grapadora Clips Post-it Archivador Teléfono Calendario Agenda Correo Reunión Oficina Jefe Empleado Café Fotocopiadora Proyector Presentación Pizarra digital Auriculares Micrófono Cámara web Escáner Bolígrafo Portaminas Sacapuntas Tiza Tablero Pupitre Casillero Timbre Ascensor Pasillo Baño Cantina Cafetería Laboratorio Gimnasio Cancha Teatro Auditorio Diploma Medalla Trofeo Certificado Graduación Bibliotecario Secretaria Director Portero Conserje Videollamada Llamada Informe Contrato".split(' '),
    "Medio":"Proyector Pizarra digital Tableta gráfica Impresora 3D Cortadora láser Microscopio Telescopio Balanza Mechero Tubo de ensayo Probeta Matraz Modelo anatómico Globo terráqueo Esqueleto Mapa topográfico Compás Transportador Calibrador Regla T Escuadra Plumilla Rotulador Resaltador Perforadora Encuadernadora Trituradora Archivador Carpeta colgante Caja de archivo Sello Papelera Papel reciclado Puesto de trabajo Cubículo Sala de juntas Sala de conferencias Recepción Sala de espera Archivo Almacén Servidor Rack Router Switch Pantalla Cámara web Micrófono Altavoz Auriculares Teléfono IP Computador portátil Monitor Dock Teclado mecánico Ratón ergonómico Tableta Lector de tarjetas Escáner de códigos Fotocopiadora Fax Máquina de café Dispensador de agua Pizarra magnética Pizarra de corcho Panel acústico Escritorio de pie Silla ergonómica Archivador metálico Destructora de papel Tarjeta de acceso Lector biométrico Cámara de seguridad Extintor Botiquín Señal de salida Plano de evacuación Casco de laboratorio Bata Guantes Gafas de seguridad Estación meteorológica Robot educativo Kit de electrónica Placa Arduino Robot móvil Dron educativo Célula solar Generador Maqueta Rompecabezas 3D Mapa mural".split(' '),
    "Difícil":"Microscopio electrónico Espectrofotómetro Centrífuga Incubadora Autoclave Balanza analítica Cromatógrafo Espectrómetro Osciloscopio Multímetro Fuente de alimentación Generador de funciones Placa de circuito Protoboard Soldador Impresora 3D de resina Cortadora láser Fresadora CNC Plotter de corte Tableta digitalizadora Pantalla interactiva Pizarra colaborativa Sistema de videoconferencia Teleprompter Cámara PTZ Mezclador de audio Interfaz de audio Micrófono de condensador Servidor Rack de servidores NAS Firewall Switch gestionable Punto de acceso Lector biométrico Control de acceso Archivador ignífugo Destructora industrial Encuadernadora térmica Plastificadora Guillotina de papel Prensa de encuadernación Máquina de escribir Proyector de transparencias Retroproyector Microfilm Lector de microfilm Pupitre universitario Mesa de laboratorio Campana extractora Ducha de emergencia Lavaojos Armario de químicos Balanza de precisión Micrótomo Modelo molecular Esqueleto articulado Planetario Telescopio reflector Observatorio escolar Estación meteorológica Anemómetro Pluviómetro Barómetro Sismógrafo Kit de robótica Brazo robótico Robot humanoide Dron Impresora Braille Máquina Perkins Mapa celeste Globo de plasma Péndulo de Newton Máquina de Atwood Generador de Van de Graaff Motor eléctrico Transformador Bobina de Tesla Panel fotovoltaico Célula de combustible Modelo de ADN Modelo de célula Modelo del sistema solar Herbario Colección de minerales Colección de fósiles Sala de servidores Centro de datos Laboratorio de computación Aula híbrida Aula virtual Biblioteca digital Archivo histórico".split(' ')
  },
  "Superhéroes y fantasía": {
    "Fácil":"Superman Batman Spider-Man Hulk Thor Iron Man Capitán América Wonder Woman Flash Aquaman Supergirl Robin Groot Rocket Shrek Dragón Unicornio Hada Bruja Mago Rey Reina Princesa Caballero Pirata Ninja Samurái Sirena Vampiro Momia Fantasma Zombi Gigante Troll Duende Elfo Hombre lobo Centauro Pegaso Fénix Grifo Kraken Cíclope Minotauro Hombre invisible Genio Aladino Varita Escoba voladora Castillo Dragón Tesoro Corona Espada Escudo Armadura Capa Máscara Portal Poción Caldero Libro mágico Mapa del tesoro Anillo mágico Cristal mágico Trono Mazmorra Torre Bosque encantado Isla pirata Nave espacial Robot Alienígena Cazafantasmas Detective Agente secreto Espía Villano Héroe Princesa guerrera Rey mago Hada madrina Genio de la lámpara Gigante de hielo Monstruo marino Sirena Elfo Enano Hobbit Orco Goblin Mago Hechicero Bruja".split(' '),
    "Medio":"Doctor Strange Black Panther Deadpool Wolverine Magneto Professor X Loki Thanos Ant-Man Black Widow Hawkeye Daredevil Venom Green Lantern Harley Quinn Catwoman Joker Aquaman Shazam Cyborg Star-Lord Gamora Nebula Groot Rocket Ultron Vision Wanda Falcon Winter Soldier Nick Fury Mystique Storm Cyclops Jean Grey Beast Raven Hellboy Spawn Constantine Mandalorian Gandalf Dumbledore Voldemort Gollum Sauron Saruman Aragorn Legolas Frodo Bilbo Smaug Dobby Hagrid Draco Malfoy Hermione Snape Dementor Basilisco Hombre lobo Drácula Frankenstein Momia Kraken Medusa Minotauro Quimera Grifo Fénix Pegaso Centauro Cíclope Esfinge Hidra Cerbero Banshee Poltergeist Fantasma Goblin Orco Troll Enano Elfo Hada Hechicero Alquimista Nigromante Paladín Bárbaro Arquero Ranger Monje Samurái Ninja Pirata Cazarrecompensas Vampiro".split(' '),
    "Difícil":"Galactus Dormammu Mephisto Darkseid Brainiac Doomsday Apocalypse Onslaught Kang Ultron Sentinel Silver Surfer Ghost Rider Moon Knight Blade Punisher Rorschach V de Vendetta Swamp Thing Sandman Mister Mxyzptlk Doctor Fate Zatanna Raven Starfire Deathstroke Black Adam Sinestro Doom Magneto Thanos con Guantelete Infinity Gauntlet Mother Box Kryptonite Cosmic Cube Tesseract Mjolnir Stormbreaker Batarang Lazo de la verdad Escudo del Capitán América Armadura de Iron Man Traje de Spider-Man Batmóvil Batiseñal Fortaleza de la Soledad Asgard Wakanda Gotham Mordor Minas Tirith Hogwarts Diagon Alley Azkaban Rivendel Isengard Shire Narnia Camelot Avalon Valhalla Olympus Atlantis Underworld Mundo mágico Bosque prohibido Cámara secreta Reliquias de la Muerte Anillo Único Espada Excalibur Espada Andúril Martillo Mjolnir Piedra filosofal Mapa del Merodeador Capa de invisibilidad Varita de saúco Esfera del Dragón Poké Ball Trifuerza Master Sword Hyrule Mundo de Minecraft Ender Dragon Wither Creeper Nether Enderman Portal del Nether Kratos Link Zelda Ganondorf Bowser Kirby Sonic".split(' ')
  },
  "Fiestas y celebraciones": {
    "Fácil":"Cumpleaños Boda Navidad Halloween Pascua Carnaval Graduación Fiesta Piñata Pastel Regalo Velas Globos Confeti Disfraz Máscara Corona Invitación Tarjeta Foto Baile Música DJ Comida Bebida Brindis Familia Amigos Pareja Novios Anillo Ramo Iglesia Ceremonia Recepción Cena Torta Helado Dulces Chocolates Caramelos Palomitas Asado Parrillada Picnic Playa Camping Fuegos artificiales Luces Árbol de Navidad Papá Noel Reno Muñeco de nieve Huevo de Pascua Conejo de Pascua Bruja Fantasma Calabaza Esqueleto Vampiro Monstruo Sombrero de fiesta Silbato Serpentina Maraca Trompeta Mesa Sillas Mantel Vasos Platos Cubiertos Invitado Anfitrión Discurso Abrazo Beso Canción Sorpresa Selfie Video Pastel de cumpleaños Caja de regalo Papel regalo Cinta Moño Souvenir Diploma Medalla Trofeo".split(' '),
    "Medio":"Despedida de soltero Despedida de soltera Aniversario Baby shower Revelación de género Bautizo Primera comunión Confirmación Quinceañera Fiesta de graduación Fiesta de disfraces Fiesta temática Fiesta sorpresa Cena romántica Aniversario de bodas Brindis de boda Primer baile Lanzamiento del ramo Corte de la torta Marcha nupcial Fotomatón Cabina de fotos Karaoke Concurso de baile Búsqueda del tesoro Intercambio de regalos Amigo secreto Rifa Concurso Tómbola Feria Festival Carnaval Desfile Fogata Campamento Picnic Barbacoa Cena familiar Almuerzo familiar Fiesta de piscina Fiesta en la playa Fiesta de pijamas Noche de juegos Noche de películas Maratón Cuenta regresiva Fuegos artificiales Linternas Faroles Árbol de Navidad Pesebre Reyes Magos Trineo Reno Muñeco de nieve Casa embrujada Truco o trato Calabaza tallada Disfraz Máscara veneciana Desfile de carnaval Confeti Serpentina Piñata Banda musical Orquesta DJ Discoteca Pista de baile Escenario Micrófono Presentador Animador Fotógrafo Videógrafo Invitación digital Lista de regalos Mesa de dulces Mesa de postres Barra de bebidas Buffet Catering Decoración Guirnalda Centro de mesa Arco de globos Photocall Libro de firmas Recuerdo de boda Souvenir Medalla Trofeo Diploma".split(' '),
    "Difícil":"Ceremonia de renovación de votos Fiesta de compromiso Cena de ensayo Despedida conjunta Baby shower sorpresa Revelación con confeti Ceremonia civil Ceremonia religiosa Recepción nupcial Cóctel de bienvenida Banquete de bodas Primer baile de los novios Lanzamiento del ramo Lanzamiento de la liga Corte de la torta Brindis de honor Discurso del padrino Discurso de la madrina Libro de firmas Mesa de regalos Photocall Fotomatón 360 Cabina de video Búsqueda del tesoro Escape room Karaoke temático Concurso de disfraces Concurso de talentos Concurso de baile Batalla de bandas Desfile de carrozas Festival de luces Festival de faroles Festival de cometas Carnaval nocturno Procesión de Semana Santa Posada navideña Noche de Año Nuevo Cuenta regresiva de Año Nuevo Fuegos artificiales Lluvia de confeti Cañón de confeti Máquina de humo Máquina de burbujas Espectáculo de luces Show de magia Espectáculo pirotécnico Castillo de fuegos artificiales Árbol de Navidad gigante Pesebre viviente Reyes Magos Papá Noel en trineo Casa embrujada Laberinto de terror Zombie walk Desfile de Halloween Calabaza gigante Concurso de calabazas Truco o trato Piñata gigante Mesa de dulces Fuente de chocolate Barra de cócteles sin alcohol Estación de postres Carrito de helados Food truck Catering temático Cena de gala Banquete medieval Fiesta de época Fiesta de máscaras Baile de máscaras Fiesta tropical Fiesta hawaiana Fiesta mexicana Fiesta años 80 Fiesta años 90 Fiesta disco Fiesta de casino Noche de trivia Noche de bingo Torneo familiar Olimpiadas familiares Entrega de premios Ceremonia de graduación Lanzamiento de birrete Anuario escolar Baile de graduación Reunión familiar Fiesta de jubilación Fiesta de inauguración Fiesta de despedida Fiesta de bienvenida".split(' ')
  },
  "Dinosaurios": {
    "Fácil":"Tiranosaurio rex Triceratops Velociraptor Diplodocus Estegosaurio Braquiosaurio Pterodáctilo Iguanodonte Anquilosaurio Espinosaurio Parasaurolophus Alosaurio Carnotauro Mosasaurio Arqueoptérix Pachicefalosaurio Gallimimo Compsognato Brontosaurio Huevo de dinosaurio Fósil Hueso Huella de dinosaurio Nido de dinosaurio Esqueleto Museo Paleontólogo Excavación Diente Garra Cráneo Cola Cuerno Placa dorsal Volcán Selva prehistórica Pantano prehistórico Meteorito Asteroide Bosque prehistórico Lago prehistórico Montaña Cueva Pteranodón Ictiosaurio Plesiosaurio Ammonite Libélula gigante Helecho gigante Palmera prehistórica Árbol gigante Huella fósil Hueso gigante Mandíbula Dinosaurio volador Dinosaurio marino Dinosaurio herbívoro Dinosaurio carnívoro Jurásico Cretácico Triceratops bebé Raptor T-Rex Dinosaurio con plumas Huevo roto Volcán en erupción Fósil de diente Dinosaurio rugiendo Dinosaurio caminando Dinosaurio comiendo Dinosaurio corriendo Dinosaurio peleando Dinosaurio durmiendo Dinosaurio nadando Dinosaurio volando Huevo gigante Nido Fósil en piedra Ámbar Mosquito en ámbar Tierra prehistórica Cráter Extinción".split(' '),
    "Medio":"Tiranosaurio rex Triceratops Velociraptor Diplodocus Estegosaurio Braquiosaurio Anquilosaurio Espinosaurio Parasaurolophus Alosaurio Carnotauro Mosasaurio Iguanodonte Pachicefalosaurio Gallimimo Compsognato Pteranodón Quetzalcoatlus Plesiosaurio Ictiosaurio Ammonite Arqueoptérix Oviraptor Protoceratops Therizinosaurus Deinonychus Dilophosaurus Baryonyx Suchomimus Majungasaurus Giganotosaurus Argentinosaurus Patagotitan Mamenquisaurio Apatosaurio Camarasaurio Ceratosaurio Torosaurio Styracosaurus Centrosaurus Edmontosaurus Hadrosaurio Pachyrhinosaurus Euoplocephalus Nodosaurio Sauropelta Microraptor Anchiornis Troodon Oviraptor Velociraptor cazando T-Rex cazando Triceratops peleando Dinosaurio en manada Huevo fósil Nido fósil Huella fósil Coprolito Ámbar fósil Bosque jurásico Mar jurásico Pantano cretácico Volcán prehistórico Meteorito Extinción masiva Pangea Paleontólogo Excavación Brocha Martillo geológico Cincel Museo de historia natural Esqueleto de T-Rex Esqueleto de triceratops Reconstrucción dinosaurio Diente fósil Garra fósil Cuerno fósil Placa fósil Hueso fosilizado Cola fósil Mandíbula fósil Cráneo fósil Nido de huevos Dinosaurio herbívoro Dinosaurio carnívoro Dinosaurio volador Reptil marino Mamífero prehistórico Megafauna Mamut Mastodonte Megaterio Gliptodonte".split(' '),
    "Difícil":"Tiranosaurio rex Triceratops Velociraptor Spinosaurus Giganotosaurus Argentinosaurus Patagotitan Mamenchisaurus Quetzalcoatlus Therizinosaurus Deinocheirus Oviraptor Citipati Troodon Microraptor Anchiornis Yi qi Archaeopteryx Confuciusornis Hesperornis Mosasaurus Pliosaurus Liopleurodon Elasmosaurus Ichthyosaurus Dunkleosteus Megalodon Helicoprion Opabinia Anomalocaris Hallucigenia Tiktaalik Dimetrodon Edaphosaurus Postosuchus Coelophysis Dilophosaurus Baryonyx Suchomimus Carcharodontosaurus Majungasaurus Carnotaurus Ceratosaurus Allosaurus Acrocanthosaurus Torvosaurus Saurophaganax Stegosaurus Kentrosaurus Ankylosaurus Euoplocephalus Sauropelta Nodosaurus Pachycephalosaurus Stygimoloch Dracorex Parasaurolophus Corythosaurus Lambeosaurus Edmontosaurus Maiasaura Iguanodon Ouranosaurus Tenontosaurus Diplodocus Apatosaurus Brachiosaurus Camarasaurus Saltasaurus Amargasaurus Dreadnoughtus Futalognkosaurus Fósil de coprolito Fósil de ámbar Paleontología Estratigrafía Formación geológica Pangea Gondwana Laurasia Cretácico tardío Jurásico tardío Triásico Extinción del Cretácico Cráter de Chicxulub Impacto de asteroide Mar de Tetis Paleoclima Huella tridáctila Icnita Rastro fósil Huevo fósil Nido fósil Yacimiento fósil Excavación paleontológica Preparación fósil Reconstrucción esquelética Montaje de museo Paleoartista Paleobotánica Paleoecología Reptil volador Reptil marino Mamífero mesozoico Megafauna del Pleistoceno Smilodon Mamut lanudo Megaterio Gliptodonte Aves del terror Titanis Moa Dodo Quagga Tilacino Extinción".split(' ')
  },
  "Música": {
    "Fácil":"Guitarra Piano Batería Violín Flauta Trompeta Saxofón Tambor Maraca Micrófono Parlante Audífonos Radio Canción Baile Cantante Músico DJ Orquesta Banda Coro Concierto Escenario Disco Vinilo CD Cinta Nota musical Clave de sol Pentagrama Canción de cuna Rock Pop Salsa Cumbia Reguetón Vallenato Merengue Tango Samba Jazz Blues Rap Hip hop Karaoke Serenata Guitarra eléctrica Bajo Teclado Ukulele Arpa Acordeón Armónica Pandereta Triángulo Platillos Bongo Conga Caja Clarinete Oboe Fagot Trombón Tuba Corno Violonchelo Contrabajo Viola Banjo Mandolina Xilófono Marimba Campana Silbato Metrónomo Atril Partitura Disco de oro Estudio Grabación Ecualizador Mezclador Amplificador Cable Tarima Luces Coreografía Festival Entrada Boleto Fan Aplausos Bis Estrella Grupo Dúo Trío".split(' '),
    "Medio":"Guitarra eléctrica Bajo Batería Teclado Sintetizador Samplers Caja de ritmos Mezclador Amplificador Pedal de efectos Distorsión Micrófono de condensador Micrófono dinámico Interfaz de audio Auriculares de estudio Monitores de estudio Metrónomo Afinador Atril Partitura Director de orquesta Concertino Coro Cuarteto de cuerda Quinteto Banda de jazz Big band Orquesta sinfónica Orquesta de cámara Banda de rock Banda de música DJ Productor musical Ingeniero de sonido Compositor Arreglista Letrista Cantautor Solista Rapero Beatboxer Bailarín Coreógrafo Salsa Cumbia Vallenato Merengue Bachata Tango Samba Flamenco Fado Reggae Ska Rock Punk Metal Disco Funk Soul Blues Jazz Gospel Country Bluegrass Folk Electrónica House Techno Trance Dubstep Drum and bass Reguetón Trap Hip hop Freestyle Batalla de rap Karaoke Serenata Concierto acústico Concierto eléctrico Festival musical Gira Prueba de sonido Backstage Camerino Tarima Torre de sonido Mesa de mezclas Consola de luces Videoclip Álbum Sencillo EP Lista de reproducción Portada Firma de autógrafos".split(' '),
    "Difícil":"Sintetizador modular Theremin Ondas Martenot Órgano Hammond Clavicémbalo Celesta Mellotron Moog Sampler Secuenciador Caja de ritmos Controlador MIDI Interfaz de audio Compresor Limitador Ecualizador paramétrico Reverb Delay Chorus Flanger Phaser Distorsión Overdrive Wah-wah Pedal de loop Micrófono de cinta Micrófono de condensador Micrófono de válvulas Micrófono binaural Grabación multipista Masterización Mezcla de audio Ingeniería de sonido Producción musical Arreglo orquestal Partitura sinfónica Dirección orquestal Concertino Sección de cuerdas Sección de vientos Sección de percusión Cuarteto de cuerda Quinteto de metales Octeto Coro polifónico Fuga Sonata Sinfonía Concierto clásico Ópera Aria Recitativo Obertura Rondó Nocturno Preludio Etude Canon Madrigal Cantata Oratorio Réquiem Jazz fusión Bebop Swing Cool jazz Free jazz Dixieland Funk Soul Motown Afrobeat Bossa nova Samba Tango nuevo Flamenco Reggae dub Dancehall Drum and bass Ambient Trance Techno House Garage Breakbeat Trip hop Lo-fi Synthwave Vaporwave Trap Drill Freestyle Beatboxing Scratching Turntablism Sampling Looping Live looping Soundcheck Backline Rider técnico Backstage Headliner Bis Festival Concierto sinfónico".split(' ')
  }
};

// La lista anterior usa espacios como separadores para mantener el archivo manejable.
// Normalizamos algunas expresiones de varias palabras que deben permanecer juntas.
const MULTIWORD_FIXES = {
  "Animales":["Pez payaso","Pez globo","Caballito de mar","Estrella de mar","Oso polar","Oso panda","Camello bactriano","Pez espada","Pez martillo","Pez león","Anguila eléctrica","Pez piedra","Pez luna","Pez arquero","Calamar vampiro","Calamar gigante","Pulpo dumbo","Camarón mantis","Cangrejo herradura","Rana dardo venenosa","Serpiente taipán","Mamba negra","Cobra real"],
  "Profesiones":["Chef pastelero","Controlador aéreo","Capitán de barco","Director de cine","Diseñador gráfico","Diseñador industrial","Desarrollador web","Técnico de laboratorio","Técnico de redes","Piloto de carreras","Mecánico de competición","Entrenador de perros","Fotoperiodista","Ingeniero aeroespacial","Ingeniero nuclear","Ingeniero biomédico","Ingeniero naval","Ingeniero ambiental","Científico de datos","Arquitecto de software","Ingeniero DevOps","Especialista en ciberseguridad","Administrador de bases de datos"],
  "Objetos":["Máquina de escribir","Máquina de coser","Telescopio espacial","Brújula náutica","Proyector de cine","Barómetro","Cámara térmica","Cámara de seguridad","Caja registradora","Terminal POS","Máquina expendedora","Contenedor marítimo","Panel solar","Turbina eólica","Proyector holográfico"],
  "Lugares":["Estación de tren","Estación espacial","Parque de diversiones","Estudio de cine","Set de televisión","Estudio de grabación","Sala de conciertos","Campo de golf","Pista de esquí","Puerto deportivo","Terminal de cruceros","Planta eléctrica","Reserva natural","Parque nacional","Playa tropical","Isla volcánica","Arrecife de coral","Cueva de hielo","Gran Barrera de Coral","Ciudad Prohibida","Palacio de Versalles","Ópera de Sídney","Empire State Building","Times Square","Las Vegas Strip","Silicon Valley","Wall Street","Puente Golden Gate","Puente de Brooklyn","Isla de Pascua","Líneas de Nazca","Valle de los Reyes","Estación espacial internacional","Centro de control espacial","Laboratorio submarino","Ciudad submarina","Plataforma petrolera","Parque jurásico","Castillo medieval","Aldea vikinga","Templo budista","Monasterio tibetano","Ciudad perdida"],
  "Acciones":["Saltar la cuerda","Hacer ejercicio","Tomar una foto","Abrir un regalo","Inflar un globo","Montar bicicleta","Montar patineta","Montar a caballo","Cruzar la calle","Esperar el bus","Tomar el metro","Comprar comida","Pagar una cuenta","Contar dinero","Firmar un documento","Escribir una carta","Enviar un mensaje","Hacer una llamada","Tomar una selfie","Grabar un video","Escuchar música","Tocar guitarra","Tocar piano","Tocar batería","Cantar en público","Bailar salsa","Bailar tango","Hacer yoga","Levantar pesas","Jugar fútbol","Jugar tenis","Lanzar una bola","Nadar de espaldas","Hacer clavados","Cocinar una receta","Hacer una torta","Preparar café","Servir una mesa","Lavar un carro","Cambiar una llanta","Arreglar una bicicleta","Pintar una pared","Armar un mueble","Regar el jardín","Podar un árbol","Cortar el césped","Pasear al perro","Bañar al perro","Alimentar una mascota","Dar un regalo","Recibir un regalo","Romper una piñata","Soplar velas","Chocar los cinco","Dar un abrazo","Lanzar un beso","Guiñar un ojo","Tomar apuntes","Hacer una presentación","Borrar una pizarra","Ordenar una habitación","Hacer la cama","Tender ropa"],
  "Películas y personajes":["Spider-Man","Iron Man","Capitán América","Black Widow","Black Panther","Professor X","Star-Lord","Winter Soldier","Doctor Strange","Darth Vader","Jack Sparrow","Indiana Jones","Harry Potter","Kung Fu Panda","Gato con Botas","Cómo entrenar a tu dragón","Emperatriz Furiosa"],
  "Ropa y accesorios":["Traje de baño","Gafas de sol","Guantes de cocina","Chaleco salvavidas","Traje de astronauta","Disfraz de superhéroe","Disfraz de pirata","Disfraz de payaso","Disfraz de vampiro","Uniforme de policía","Uniforme de bombero","Uniforme de chef","Uniforme militar","Uniforme deportivo","Poncho andino","Botas de vaquero","Traje de neopreno","Casco de bicicleta","Casco de motocicleta","Casco de astronauta","Guantes de boxeo","Cinturón de karate","Anillo de compromiso","Velo de novia","Guantes largos","Aletas de buceo"],
  "Transporte":["Globo aerostático","Bus escolar","Bus turístico","Bus articulado","Camión de bomberos","Tren de carga","Tren bala","Coche deportivo","Bicicleta de montaña","Bicicleta de carrera","Bicicleta eléctrica","Scooter eléctrico","Trineo de perros","Moto de nieve","Avión de carga","Moto acuática","Lancha rápida","Teleférico de montaña","Funicular de montaña","Transbordador espacial","Cápsula espacial","Vehículo lunar","Cohete reutilizable","Dron submarino","Submarino nuclear","Submarino de investigación","Barco rompehielos","Portaaviones","Buque hospital","Ferry de alta velocidad","Tren maglev","Tren sin conductor","Camión minero","Grúa telescópica","Moto de trial","Bicicleta de pista","Bicicleta de descenso","Góndola veneciana"],
  "Casa y hogar":["Aspiradora robot","Lavavajillas","Horno eléctrico","Freidora de aire","Olla a presión","Cafetera espresso","Procesador de alimentos","Calentador de agua","Purificador de aire","Aire acondicionado portátil","Ventilador de techo","Robot de cocina","Máquina de coser","Caja fuerte","Cámara de seguridad","Detector de humo","Timbre inteligente","Cerradura electrónica","Sillón reclinable","Mesa de centro","Caja de herramientas","Banco de trabajo","Sierra eléctrica","Hidrolavadora","Cortacésped","Horno de pizza","Casa del árbol","Sistema de riego automático","Invernadero automatizado","Paneles solares","Batería doméstica","Bomba de calor","Cerradura biométrica","Videoportero","Red mesh","Rack de comunicaciones","Home theater","Proyector 4K","Sistema multiroom","Robot limpia piscinas","Horno de vapor","Horno combinado","Molino de café","Encimera de inducción","Campana extractora","Lavadora inteligente","Secadora con bomba de calor","Piscina infinita","Huerto hidropónico"],
  "Escuela y oficina":["Pizarra digital","Tableta gráfica","Impresora 3D","Cortadora láser","Tubo de ensayo","Globo terráqueo","Mapa topográfico","Regla T","Carpeta colgante","Sala de juntas","Sala de conferencias","Puesto de trabajo","Teléfono IP","Computador portátil","Teclado mecánico","Ratón ergonómico","Lector biométrico","Estación meteorológica","Placa Arduino","Dron educativo","Microscopio electrónico","Espectrofotómetro","Balanza analítica","Fuente de alimentación","Generador de funciones","Impresora 3D de resina","Fresadora CNC","Sistema de videoconferencia","Cámara PTZ","Interfaz de audio","Rack de servidores","Switch gestionable","Control de acceso","Archivador ignífugo","Guillotina de papel","Mesa de laboratorio","Campana extractora","Ducha de emergencia","Lavaojos","Generador de Van de Graaff","Modelo del sistema solar","Colección de minerales","Centro de datos","Laboratorio de computación","Biblioteca digital"],
  "Superhéroes y fantasía":["Doctor Strange","Black Panther","Capitán América","Wonder Woman","Green Lantern","Harley Quinn","Professor X","Star-Lord","Winter Soldier","Fortaleza de la Soledad","Anillo Único","Piedra filosofal","Capa de invisibilidad","Varita de saúco","Esfera del Dragón","Master Sword","Portal del Nether","Ender Dragon","Batimóvil","Batiseñal","Lazo de la verdad","Escudo del Capitán América","Armadura de Iron Man","Traje de Spider-Man","Espada Excalibur","Espada Andúril","Martillo Mjolnir"],
  "Fiestas y celebraciones":["Baby shower","Revelación de género","Primera comunión","Fiesta de graduación","Fiesta de disfraces","Fiesta sorpresa","Cena romántica","Aniversario de bodas","Brindis de boda","Primer baile","Lanzamiento del ramo","Corte de la torta","Fotomatón","Cabina de fotos","Búsqueda del tesoro","Intercambio de regalos","Amigo secreto","Fiesta de pijamas","Noche de juegos","Fiesta de piscina","Fiesta en la playa","Casa embrujada","Truco o trato","Calabaza tallada","Mesa de dulces","Arco de globos","Libro de firmas","Ceremonia de renovación de votos","Fiesta de compromiso","Cena de ensayo","Recepción nupcial","Cóctel de bienvenida","Primer baile de los novios","Lanzamiento de la liga","Photocall","Fotomatón 360","Escape room","Concurso de disfraces","Festival de luces","Cuenta regresiva de Año Nuevo","Cañón de confeti","Máquina de humo","Pesebre viviente","Laberinto de terror","Zombie walk","Fiesta años 80","Fiesta años 90","Fiesta de casino","Olimpiadas familiares","Lanzamiento de birrete"],
  "Dinosaurios":["Tiranosaurio rex","Triceratops","Velociraptor","Diplodocus","Estegosaurio","Braquiosaurio","Pterodáctilo","Iguanodonte","Anquilosaurio","Espinosaurio","Parasaurolophus","Alosaurio","Carnotauro","Mosasaurio","Arqueoptérix","Pachicefalosaurio","Pteranodón","Quetzalcoatlus","Plesiosaurio","Ictiosaurio","Giganotosaurus","Argentinosaurus","Patagotitan","Therizinosaurus","Deinocheirus","Oviraptor","Microraptor","Troodon","Dilophosaurus","Baryonyx","Suchomimus","Carcharodontosaurus","Majungasaurus","Styracosaurus","Euoplocephalus","Nodosaurus","Maiasaura","Iguanodon","Dreadnoughtus","Futalognkosaurus","Mosasaurus","Pliosaurus","Liopleurodon","Elasmosaurus","Dunkleosteus","Megalodon","Dimetrodon","Tiktaalik","Anomalocaris","Hallucigenia","Pangea","Gondwana","Laurasia","Cráter de Chicxulub","Extinción del Cretácico","Paleontología","Icnita","Coprolito","Fósil de ámbar","Excavación paleontológica","Reconstrucción esquelética","Paleoartista","Paleobotánica","Smilodon","Mamut lanudo","Megaterio","Gliptodonte","Dodo","Tilacino"],
  "Música":["Guitarra","Piano","Batería","Violín","Flauta","Trompeta","Saxofón","Tambor","Maraca","Micrófono","Parlante","Audífonos","Radio","Canción","Baile","Cantante","Músico","DJ","Orquesta","Banda","Coro","Concierto","Escenario","Disco","Vinilo","CD","Nota musical","Clave de sol","Pentagrama","Rock","Pop","Salsa","Cumbia","Reguetón","Vallenato","Merengue","Tango","Samba","Jazz","Blues","Rap","Hip hop","Karaoke","Serenata","Guitarra eléctrica","Bajo","Teclado","Ukulele","Arpa","Acordeón","Armónica","Pandereta","Triángulo","Platillos","Bongo","Conga","Clarinete","Oboe","Fagot","Trombón","Tuba","Corno","Violonchelo","Contrabajo","Viola","Banjo","Mandolina","Xilófono","Marimba","Metrónomo","Partitura","Estudio de grabación","Mezclador","Amplificador","Festival","Videoclip","Álbum","Sencillo","Lista de reproducción","Sintetizador","Caja de ritmos","Productor musical","Ingeniero de sonido","Beatboxer","Coreógrafo","Big band","Orquesta sinfónica","Ópera","Aria","Sonata","Sinfonía","Bebop","Swing","Funk","Soul","Afrobeat","Bossa nova","House","Techno","Trance","Trap","Drum and bass"]
};

// Agrega los bancos ampliados a las categorías existentes y crea las nuevas.
for (const [category, levels] of Object.entries(EXTRA_BANKS)) {
  if (!DATA[category]) DATA[category] = { "Fácil": [], "Medio": [], "Difícil": [] };
  for (const level of ["Fácil","Medio","Difícil"]) {
    DATA[category][level] = [...new Set([...(DATA[category][level] || []), ...(levels[level] || [])])];
  }
}

const NEW_CATEGORIES = {
  "Viajes y vacaciones": {
    "Fácil":"Maleta Pasaporte Avión Hotel Playa Piscina Cámara Mapa Mochila Carretera Bus Tren Barco Crucero Tienda Souvenir Foto Cámara Bloqueador Sombrero Gafas de sol Toalla Traje de baño Sandalias Helado Coco Palmera Arena Mar Ola Sol Montaña Camping Carpa Fogata Sendero Guía Turista Monumento Museo Restaurante Café Aeropuerto Terminal Taxi Alquiler de carro Hotel Habitación Ascensor Llave Recepción Piscina Maleta Boleto Pasaje Embarque Ventana Aeropuerto Control de seguridad Aduana Equipaje Recuerdo Imán Postal Brújula Mapa GPS Binoculares Paraguas Impermeable Chaqueta,".split(' '),
    "Medio":"Escala de vuelo Conexión de vuelo Sala VIP Puerta de embarque Control migratorio Aduana Equipaje perdido Maleta de mano Mochila de viaje Hostal Resort Bungalow Cabaña Villa Apartamento turístico Camping Glamping Senderismo Trekking Buceo Snorkel Surf Kayak Rafting Parapente Esquí Snowboard Teleférico Funicular Crucero Ferry Yate Catamarán Puerto Marina Faro Isla volcánica Arrecife Coral Laguna Cenote Cascada Cañón Glaciar Desierto Oasis Safari Reserva natural Parque nacional Mercado local Feria artesanal Tour guiado Excursión Fotografía de paisaje Pasaporte Sellado Visado Seguro de viaje Cambio de moneda Tarjeta de embarque Rentar carro Gasolinera Peaje Carretera panorámica Mirador Atardecer Amanecer,".split(' '),
    "Difícil":"Turismo de aventura Ecoturismo Turismo gastronómico Turismo cultural Turismo rural Turismo espacial Mochilero Viajero frecuente Nómada digital Workation Escala internacional Tránsito aeroportuario Lounge aeroportuario Migración internacional Aduana internacional Visado de tránsito Permiso de entrada Control fronterizo Zona Schengen Duty free Overbooking Equipaje sobredimensionado Reclamación de equipaje Cancelación de vuelo Retraso de vuelo Conexión perdida Jet lag Cambio horario Husos horarios Itinerario de viaje Road trip Ruta panorámica Camino de Santiago Safari fotográfico Expedición Polar Crucero de expedición Buceo nocturno Inmersión profunda Pecio submarino Espeleobuceo Rafting extremo Barranquismo Escalada en hielo Trekking de altura Montañismo Alta montaña Campamento base Glamping de lujo Resort todo incluido Villa sobre el agua Bungalow sobre el agua Crucero fluvial Tren panorámico Tren nocturno Ferry internacional Catamarán de expedición Velero oceánico Kayak de travesía Parapente acrobático Globo aerostático sobre el desierto Aurora boreal Eclipse solar Totalidad del eclipse Observatorio astronómico Reserva marina Patrimonio mundial Sitio arqueológico Ruinas antiguas Ciudad perdida Ruta del vino Ruta del café Ruta gastronómica Mercado flotante Pueblo medieval Ciudad amurallada Isla desierta Volcán activo Glaciar azul Salar de Uyuni Machu Picchu Patagonia Antártida".split(' ')
  },
  "Cuerpo y salud": {
    "Fácil":"Cabeza Ojo Oreja Nariz Boca Diente Lengua Mano Brazo Pierna Pie Rodilla Codo Hombro Corazón Pulmón Cerebro Estómago Espalda Cabello Pelo Uña Dedo Cara Cuello Pecho Barriga Sangre Hueso Músculo Médico Enfermero Hospital Clínica Ambulancia Medicina Pastilla Jarabe Termómetro Venda Curita Muleta Silla de ruedas Gafas Cepillo de dientes Pasta dental Jabón Champú Toalla Ducha Baño Dormir Comer Beber Caminar Correr Saltar Respirar Estornudar Toser Llorar Reír Sonreír Bostezar Dolor Fiebre Tos Gripe Resfriado Herida Golpe Moretón Quemadura Hielo Agua Descanso Ejercicio Gimnasio Bicicleta Natación Yoga Masaje".split(' '),
    "Medio":"Esqueleto Músculo Tendón Ligamento Articulación Columna Vertebral Cerebelo Cerebro Corazón Pulmón Hígado Riñón Intestino Estómago Páncreas Tiroides Retina Pupila Iris Oído interno Garganta Amígdala Diente muela Muela del juicio Dentista Cirujano Paramédico Fisioterapeuta Nutricionista Psicólogo Farmacéutico Dermatólogo Cardiólogo Pediatra Ambulancia Hospital quirófano Consultorio Farmacia Laboratorio Radiografía Ecografía Tomografía Resonancia Electrocardiograma Estetoscopio Termómetro Tensiómetro Glucómetro Oxímetro Jeringa Vacuna Suero Antibiótico Analgésico Vendaje Yeso Muletas Prótesis Marcapasos Inhalador Nebulizador Mascarilla Guantes Bata médica Camilla Rehabilitación Terapia Ejercicio Estiramiento Meditación Respiración Primeros auxilios RCP Desfibrilador Dieta Hidratación Sueño".split(' '),
    "Difícil":"Sistema nervioso Sistema circulatorio Sistema respiratorio Sistema digestivo Sistema endocrino Sistema inmunitario Sistema linfático Sistema musculoesquelético Hipotálamo Hipófisis Cerebelo Tronco encefálico Médula espinal Retina Córnea Cristalino Cóclea Tímpano Laringe Faringe Esófago Duodeno Yeyuno Íleon Colon Apéndice Vesícula biliar Páncreas Bazo Riñón Uréter Vejiga Próstata Tiroides Suprarrenal Hipocampo Amígdala cerebral Neurona Sinapsis Glóbulo rojo Glóbulo blanco Plaqueta Anticuerpo Antígeno Hormona Insulina Adrenalina Dopamina Serotonina Hemoglobina ADN Gen Cromosoma Microbiota Endoscopia Colonoscopia Biopsia Hemodiálisis Quimioterapia Radioterapia Anestesia Epidural Laparoscopia Cirugía robótica Trasplante Donante Receptor Prótesis biónica Marcapasos Implante coclear Resonancia magnética Tomografía computarizada Electroencefalograma Electromiografía Espirometría Audiometría Oftalmoscopía Ecocardiograma Cateterismo Fisioterapia Rehabilitación neurológica Terapia ocupacional Logopedia Fonoaudiología Medicina deportiva Medicina preventiva Telemedicina Epidemiología Inmunología Genética Neurología Cardiología Endocrinología Oncología Dermatología Traumatología Ortopedia Psiquiatría Nutrición clínica".split(' ')
  },
  "Tecnología": {
    "Fácil":"Computador Teléfono Tablet Teclado Ratón Pantalla Cámara Televisor Radio Parlante Audífonos Cargador Batería Cable Internet Wi-Fi Router Impresora Consola Videojuego Control remoto Reloj inteligente Smartwatch Dron Robot USB Memoria USB Disco duro Laptop Monitor Micrófono Cámara web Aplicación Juego Foto Video Mensaje Correo Contraseña Emoji Código QR GPS Bluetooth Altavoz Linterna Calculadora Cámara digital Videollamada Selfie Streaming Netflix YouTube Música Podcast Redes sociales Wi-Fi móvil Tablet gráfica Teclado mecánico Mouse inalámbrico Power bank".split(' '),
    "Medio":"Servidor Router Switch Firewall Punto de acceso NAS Disco SSD Disco HDD Memoria RAM Procesador Tarjeta gráfica Placa madre Fuente de poder Monitor ultrawide Webcam Micrófono USB Interfaz de audio Impresora 3D Dron Robot Arduino Raspberry Pi Sensor Cámara de seguridad Cámara IP Videoportero Cerradura inteligente Bombillo inteligente Enchufe inteligente Termostato inteligente Asistente de voz Altavoz inteligente Smart TV Consola portátil Realidad virtual Gafas VR Controlador Joystick Volante gaming Simulador Streaming Podcast Videollamada Edición de video Edición de fotos Diseño 3D Código QR NFC Bluetooth Wi-Fi 6 Wi-Fi mesh Fibra óptica 5G Satélite GPS Cloud Nube digital Copia de seguridad Cifrado Antivirus VPN Chatbot Inteligencia artificial Algoritmo Base de datos API Aplicación web Sitio web".split(' '),
    "Difícil":"Arquitectura de microservicios Kubernetes Contenedor Docker API Gateway Balanceador de carga CDN DNS DHCP Proxy Reverse proxy Firewall de aplicaciones IDS IPS SIEM Zero Trust Criptografía Blockchain Smart contract Tokenización Machine learning Deep learning Red neuronal Modelo de lenguaje Visión artificial Procesamiento de lenguaje natural Reconocimiento facial Reconocimiento de voz Síntesis de voz Realidad aumentada Realidad mixta Computación cuántica Criptografía cuántica Edge computing Serverless Data lake Data warehouse ETL Pipeline CI/CD DevOps Git Repositorio Control de versiones Pull request Merge Deploy Rollback Observabilidad Telemetría Logging Tracing Microservicio WebSocket WebRTC GraphQL REST API OAuth JWT SSO Biometría Huella digital Reconocimiento de iris Firma digital Certificado digital HSM Token OTP Autenticación multifactor Honeypot Penetration testing Vulnerability scanner Ransomware Phishing Malware Botnet DDoS Backup incremental Disaster recovery Alta disponibilidad Cluster RAID Virtualización Hipervisor Máquina virtual Bare metal IoT Gemelo digital Vehículo autónomo Robot humanoide Impresión 3D avanzada Drone autónomo Satélite CubeSat".split(' ')
  },
  "Animaciones y dibujos": {
    "Fácil":"Línea Círculo Cuadrado Triángulo Casa Árbol Sol Luna Nube Flor Persona Cara Ojo Boca Mano Pie Gato Perro Pez Pájaro Mariposa Auto Avión Barco Bicicleta Pelota Globo Corazón Estrella Corona Espada Escudo Castillo Montaña Río Lago Soláforo Semáforo Puerta Ventana Mesa Silla Cama Libro Lápiz Pincel Pintura Cámara Teléfono Computador Robot Monstruo Fantasma Zombi Héroe Villano Princesa Rey Reina Pirata Ninja Mago Bruja Dragón Unicornio Sirena Dinosaurio Cohete Planeta Astronauta Alienígena Cohete Luna Tierra Estrella fugaz Arcoíris Volcán Árbol de Navidad Regalo Pastel Piñata".split(' '),
    "Medio":"Caricatura Superhéroe Villano Robot Dragón Castillo Nave espacial Alienígena Dinosaurio Pirata Ninja Samurai Mago Bruja Sirena Vampiro Hombre lobo Fantasma Zombi Monstruo Unicornio Pegaso Fénix Grifo Kraken Cíclope Minotauro Centauro Esfinge Hada Duende Elfo Gigante Caballero Princesa Rey Reina Detective Espía Agente secreto Astronauta Científico Inventor Explorador Pirata espacial Guerrero Arquero Mago oscuro Hechicero Alquimista Poción Varita Portal Tesoro Mapa del tesoro Máquina del tiempo Portal dimensional Planeta alienígena Ciudad futurista Ciudad medieval Bosque encantado Isla pirata Volcán activo Cueva misteriosa Templo antiguo Ruinas Robot gigante Mecha Dron Nave espacial Estación espacial Rover Alienígena verde Monstruo marino Dragón volador Dragón de hielo Dragón de fuego Dinosaurio volador Dinosaurio marino Fósil Máquina del tiempo Supervillano Batimóvil Cohete secreto Laboratorio secreto".split(' '),
    "Difícil":"Storyboard Perspectiva Isométrica Anatomía humana Expresión facial Movimiento corporal Foreshortening Silueta Contraluz Textura Volumen Sombreado Luz cenital Luz lateral Luz de rim Escala de grises Caricatura editorial Concept art Matte painting Character design Environment design Creature design Prop design Storyboard cinematográfico Secuencia de acción Escena de persecución Escena de batalla Escena de transformación Portal dimensional Mundo postapocalíptico Ciudad cyberpunk Ciudad steampunk Reino submarino Ciudad flotante Colonia marciana Estación espacial abandonada Nave generacional Planeta alienígena Terraformación Robot gigante Mecha Jaeger Kaiju Dragón ancestral Fénix mitológico Kraken gigante Leviatán Cthulhu Grifo celestial Esfinge egipcia Minotauro del laberinto Medusa mitológica Cerbero Hidra de Lerna Quimera Pegaso alado Centauro guerrero Valquiria Guerrero vikingo Samurái fantasma Ninja futurista Pirata fantasma Cazador de monstruos Bruja medieval Alquimista steampunk Hechicero cósmico Mago de hielo Mago de fuego Caballero oscuro Princesa guerrera Rey hechicero Villano interdimensional Héroe cósmico Superhéroe volador Ciudad en miniatura Casa en un árbol Tren volador Isla flotante Bosque bioluminiscente Cueva de cristales Volcán submarino Océano alienígena Desierto extraterrestre".split(' ')
  }
};

// Normalización de frases compuestas para que no se rompan al usar bancos compactos.
for (const [cat, levels] of Object.entries(NEW_CATEGORIES)) {
  DATA[cat] = levels;
}

for (const cat of Object.keys(DATA)) {
  for (const level of ["Fácil","Medio","Difícil"]) {
    DATA[cat][level] = [...new Set(DATA[cat][level] || [])];
  }
}


const state = {
  category: "Animales",
  difficulty: "Fácil",
  seconds: 45,
  remaining: 45,
  round: 1,
  word: "",
  timer: null,
  paused: false,
  sound: localStorage.getItem("pictionarySound") !== "off",
  used: new Set()
};

const $ = id => document.getElementById(id);
const setup = $("setupScreen"), game = $("gameScreen"), settings = $("settingsScreen");

function renderChoices(){
  $("categoryGrid").innerHTML = Object.keys(DATA).map(c => {
    const total = Object.values(DATA[c]).reduce((n,a)=>n+a.length,0);
    return `<button class="${c===state.category?'selected':''}" data-category="${c}">${iconFor(c)} <span>${c}</span><small>${total} palabras</small></button>`;
  }).join("");
  $("difficultyGrid").innerHTML = ["Fácil","Medio","Difícil"].map(d =>
    `<button class="${d===state.difficulty?'selected':''}" data-difficulty="${d}">${d}</button>`
  ).join("");
}
function iconFor(c){
  return {"Animales":"🐾","Profesiones":"👨‍🍳","Comida":"🍕","Objetos":"🧸","Lugares":"📍","Acciones":"🏃","Películas y personajes":"🎬","Naturaleza":"🌳","Deportes":"⚽","Ropa y accesorios":"👕","Transporte":"🚗","Casa y hogar":"🏠","Escuela y oficina":"📚","Superhéroes y fantasía":"🦸","Fiestas y celebraciones":"🎉","Dinosaurios":"🦖","Música":"🎵","Viajes y vacaciones":"✈️","Cuerpo y salud":"🧠","Tecnología":"💻","Animaciones y dibujos":"✏️"}[c] || "🎨";
}
function getWord(){
  const list = DATA[state.category][state.difficulty];
  if(state.used.size >= list.length) state.used.clear();
  let i, word;
  do { i = Math.floor(Math.random()*list.length); word=list[i]; } while(state.used.has(word) && list.length>1);
  state.used.add(word);
  return word;
}
function showScreen(s){
  [setup,game,settings].forEach(x=>x.classList.add("hidden"));
  s.classList.remove("hidden");
}
function start(){
  state.round=1; state.used.clear(); state.word=getWord(); state.remaining=state.seconds; state.paused=false;
  $("result").classList.add("hidden");
  $("pauseBtn").textContent="⏸ Pausar";
  $("roundLabel").textContent="Ronda 1";
  updateWord(); updateTimer();
  showScreen(game);
  runTimer();
}
function updateWord(){
  $("word").textContent=state.word;
  $("wordCategory").textContent=state.category.toUpperCase();
  $("difficultyBadge").textContent=state.difficulty;
}
function updateTimer(){
  $("timer").textContent=state.remaining;
  $("timer").style.opacity=state.paused ? ".45" : "1";
}
function runTimer(){
  clearInterval(state.timer);
  state.timer=setInterval(()=>{
    if(state.paused)return;
    state.remaining--;
    updateTimer();
    if(state.remaining<=0){
      clearInterval(state.timer);
      finish(false);
    }
  },1000);
}
function finish(success){
  clearInterval(state.timer);
  $("result").classList.remove("hidden");
  $("resultIcon").textContent=success?"🎉":"⏰";
  $("resultTitle").textContent=success?"¡Adivinaron!":"¡Se acabó el tiempo!";
  $("resultText").textContent=success ? `La palabra era “${state.word}”.` : `La palabra era “${state.word}”.`;
  beep(success?660:220,180);
}
function nextRound(){
  state.round++;
  state.word=getWord();
  state.remaining=state.seconds;
  state.paused=false;
  $("result").classList.add("hidden");
  $("pauseBtn").textContent="⏸ Pausar";
  $("roundLabel").textContent=`Ronda ${state.round}`;
  updateWord(); updateTimer(); runTimer();
}
function beep(freq=440,duration=100){
  if(!state.sound)return;
  try{
    const C=window.AudioContext||window.webkitAudioContext;
    const ctx=new C(), osc=ctx.createOscillator(), gain=ctx.createGain();
    osc.frequency.value=freq; gain.gain.value=.05; osc.connect(gain); gain.connect(ctx.destination);
    osc.start(); setTimeout(()=>{osc.stop();ctx.close()},duration);
  }catch(e){}
}
function toast(msg){
  const t=$("toast"); t.textContent=msg; t.classList.add("show");
  setTimeout(()=>t.classList.remove("show"),1600);
}

$("categoryGrid").addEventListener("click",e=>{
  const b=e.target.closest("[data-category]"); if(!b)return;
  state.category=b.dataset.category; renderChoices();
});
$("difficultyGrid").addEventListener("click",e=>{
  const b=e.target.closest("[data-difficulty]"); if(!b)return;
  state.difficulty=b.dataset.difficulty; renderChoices();
});
document.querySelector(".time-row").addEventListener("click",e=>{
  const b=e.target.closest("[data-time]"); if(!b)return;
  state.seconds=Number(b.dataset.time); state.remaining=state.seconds;
  document.querySelectorAll("[data-time]").forEach(x=>x.classList.remove("selected")); b.classList.add("selected");
});
$("startBtn").onclick=start;
$("doneBtn").onclick=()=>finish(true);
$("nextBtn").onclick=nextRound;
$("newWordBtn").onclick=()=>{
  state.word=getWord(); state.remaining=state.seconds; updateWord(); updateTimer(); toast("Nueva palabra"); beep(520,80);
};
$("pauseBtn").onclick=()=>{
  state.paused=!state.paused;
  $("pauseBtn").textContent=state.paused?"▶ Continuar":"⏸ Pausar";
  updateTimer();
};
$("backBtn").onclick=()=>{clearInterval(state.timer);showScreen(setup)};
$("settingsBtn").onclick=()=>showScreen(settings);
$("closeSettingsBtn").onclick=()=>showScreen(setup);
$("soundBtn").onclick=()=>{
  state.sound=!state.sound;
  localStorage.setItem("pictionarySound",state.sound?"on":"off");
  $("soundBtn").textContent=state.sound?"🔊 Sonidos activados":"🔇 Sonidos desactivados";
};
$("clearBtn").onclick=()=>{localStorage.removeItem("pictionarySound");state.sound=true;$("soundBtn").textContent="🔊 Sonidos activados";toast("Configuración restablecida")};

renderChoices();
$("soundBtn").textContent=state.sound?"🔊 Sonidos activados":"🔇 Sonidos desactivados";


// Controles rápidos para partidas en computador.
document.addEventListener("keydown", e => {
  if(game.classList.contains("hidden")) return;
  if(e.code === "Space"){ e.preventDefault(); $("pauseBtn").click(); }
  if(e.key.toLowerCase() === "n") $("newWordBtn").click();
  if(e.key.toLowerCase() === "a") $("doneBtn").click();
});
